In [1]:
import numpy as np 
import torch
import matplotlib

## Forbenius Norm


In [5]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [12]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2) # sum of square of all elements and square root the sum

5.477225575051661

In [7]:
np.linalg.norm(X)

5.477225575051661

In [11]:
X_pt = torch.tensor([[1,2],[3,4.]]) #torch.norm() requires float type
torch.norm(X_pt)

tensor(5.4772)

## Matrix Multiplication

AB ≠ BA

In [14]:
A = np.array([[3,4], [5,6], [7,9]])
A

array([[3, 4],
       [5, 6],
       [7, 9]])

In [15]:
B = np.array([1,2])

In [16]:
np.dot(A,B)

array([11, 17, 25])

In [17]:
A_pt = torch.tensor([[3,4], [5,6], [7,9]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 9]])

In [33]:
B_pt = torch.tensor([1,2])
# B_pt = torch.from_numpy(B)
B_pt

tensor([1, 2])

In [21]:
torch.matmul(A_pt, B_pt)

tensor([11, 17, 25])

In [22]:
np.dot(np.array([[3,4],[5,6], [7,8]]), np.array([[1,9],[2,0]]))

array([[11, 27],
       [17, 45],
       [23, 63]])

In [29]:
torch.matmul(torch.tensor([[3,4],[5,6],[7,8]]), torch.tensor([[1,9],[2,0]]))

tensor([[11, 27],
        [17, 45],
        [23, 63]])

### Symmetric matrix
properties <br>
- Square <br>
- X<sup>T</sup> = X


In [3]:
X_sym = np.array([[0,1,2], [1,7,8], [2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [5]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Identity Matrix
Symmetric Matrix where: 
- Every element along main diagonal is 1
- All other elements are 0
- Notation: I<sub>n</sub> where n = height (or width)
- n-length vector unchanged if multiplied by I<sub>n</sub>

In [6]:
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [7]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [9]:
torch.matmul(x_pt, I)

tensor([25,  2,  5])

### Matrix Inversion
- Inverese of Matrix X is denoted by X<sup>-1</sup>
- Satisfies : X<sup>-1</sup> X = I<sub>n</sub>
- An alternative to manually solving linear eqns with substitution or elimination

In [3]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [4]:
Xinv  = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [5]:
y = np.array([4,-7])
y

array([ 4, -7])

In [7]:
w = np.dot(Xinv, y)
w

array([-1.,  4.])

y = Xw

In [8]:
np.dot(X,w)

array([ 4., -7.])

- in Pytorch

In [22]:
X_t =  torch.tensor([[4,2], [-5,3.]])
X_t

tensor([[ 4.,  2.],
        [-5.,  3.]])

In [23]:
X_tInv = torch.inverse(X_t)
X_tInv 

tensor([[ 0.1364, -0.0909],
        [ 0.2273,  0.1818]])

In [32]:
y_t = torch.tensor([4, -7.])  # y
w_t = torch.matmul(X_tInv, y)
w_t

tensor([ 1.1818, -0.3636])

In [31]:
# y = X_t,W
torch.matmul(X_t, w_t)

tensor([ 4.0000, -7.0000])

Matrix inversion where NO SOLUTION

In [33]:
X = np.array([[-4,1],[-8,2]])
X

array([[-4,  1],
       [-8,  2]])

In [ ]:
Xinv = np.linalg.inv(X)
Xinv
# Gives Singular Error as this matrix has no solutions

### Diagonal matrix
- Non zero elements along main diagonal; zeros everywhere else
- If square, denoted as diag(x) where x is vector of main-diagonal elements
- Computaionally efficent:
    - Multiplication: diag(x)y = x º y (hamadard product)
    - Inverse : diag(x)-1 = diag[1/x1...1/xn]T
        - Cant divide by zero so (x) cant include zero
- can be non square and computation still effficent
    - if h>w, simply add zeros to product       # hieght 
    - if w>h, remove elements from the product  # width

### Orthogonal Matrix
in orthogonal matrices, orthonormal vectors (set of S vectos where every vector in S is a unit vector (magnitude 1)):
- Make up all rows
- Make up all cols
- i.e. - A<sup>T</sup>A = AA<sup>T</sup> = I
    - also A<sup>T</sup> = A<sup>-1</sup>I = A<sup>-1</sup> 
- Calculating A<sup>T</sup> is cheap, therfore so is calculating A<sup>-1</sup>

EXERCISES


In [46]:
# identity matrices are orthogonal
A_i1 = np.array([1,0,0])
A_i2 = np.array([0,1,0])
np.dot(A_i1, A_i2)
# as the dot product between two cols are zero they are perpendicular thus they are orthogonal

0

In [51]:
# Both have 1 norm which means it has unit norm, both have length 1 
np.linalg.norm(A_i1)
np.linalg.norm(A_i2)

1.0

In [57]:
MR = np.array([[2/3, 1/3, 2/3], [-2/3,2/3,1/3], [1/3,2/3,-2/3]])
MR_i = np.array([2/3, 1/3, 2/3])
MR_j = np.array([-2/3,2/3,1/3])
MR_k = np.array([1/3,2/3,-2/3])

np.dot(MR_i, MR_j) # orthogonal as its dot is 0

0.0

In [59]:
np.linalg.norm(MR_i)
np.linalg.norm(MR_k)
np.linalg.norm(MR_j)
# 

1.0